### ISSUE TITLE
Create snippets with parameters and defaults

### ISSUE THREAD

**Issue by fabiandistler** [fabiandistler/pypet#3]
Develop a feature that allows users to define snippets with parameters and assign default values. This functionality will make snippets more flexible and customizable for various use cases.

**Comment by fabiandistler** [comment]
🎯 **Status Update: Already Implemented!**

Issue #3 (parameterized snippets) is **already fully implemented** in the current codebase! 

## ✅ **Current Parameter Features:**

### 📝 **Creating Parameterized Snippets:**
```bash
pypet new "docker run -p {port}:80 -v {path}:/app -e NODE_ENV={env=development} {image}" \
    -d "Run Docker container" \
    -p "port:Host port,path:Volume path,env=development:Node environment,image:Docker image"
```

### 🔧 **Parameter Types:**
- **Required:** `{name}` - Must be provided
- **Default:** `{name=default}` - Optional with fallback value
- **Descriptions:** Shown during interactive prompting

### 💻 **Usage:**
```bash
# With command-line parameters
pypet exec snippet-id -P port=3000 -P path=$PWD -P image=node:18

# Interactive prompting (will ask for missing parameters)
pypet exec snippet-id

# Copy with parameters
pypet copy snippet-id -P port=8080
```

### 📊 **Storage Format:**
Parameters are stored in TOML with full metadata:
```toml
[snippets.id.parameters.port]
name = "port"
description = "Host port to bind"

[snippets.id.parameters.env]  
name = "env"
default = "development"
description = "Node environment"
```

**This issue can be closed as completed!** 🎉
